(column-number-mode 1)
(show-paren-mode 1)
(electric-indent-mode 0)
(ido-mode 1)
(tool-bar-mode -1)
(menu-bar-mode -1) 

(ac-config-default)
(setq speedbar-initial-expansion-list-name "quick buffers")
(add-to-list 'load-path "/directory/containing/neotree/")
(setq sgml-quick-keys 'indent)
(setq web-mode-enable-current-element-highlight t)
(setq typescript-indent-level 2)
(add-to-list 'auto-mode-alist '("\\.html\\'" . web-mode))

(add-hook 'go-mode-hook
          (lambda ()
            (add-hook 'before-save-hook 'gofmt-before-save)
            (setq tab-width 4)
            (setq indent-tabs-mode 1)))
