(column-number-mode 1)
(show-paren-mode 1)
(ido-mode 1)
(ac-config-default)
(projectile-mode 1)
(global-linum-mode 1)
(neotree)

(add-to-list 'load-path "/directory/containing/neotree/")
(require 'neotree)
