(column-number-mode 1)
(show-paren-mode 1)
(electric-indent-mode 0)
(ido-mode 1)
(ac-config-default)
(setq speedbar-initial-expansion-list-name "quick buffers")
(add-to-list 'load-path "/directory/containing/neotree/")
(setq sgml-quick-keys 'indent)
